global_localization_node:
  ros__parameters:
    # x, y, z, roll, pitch, yaw (单位:度degrees)
    initialpose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # z=0.92m: ICP实测值(理论1.01m，Gazebo沉降后实测)

    kf_baselink2map:
      x: [0.001, 0.002]
      y: [0.001, 0.005]
      z: [0.00001, 0.04]
